### ISSUE TITLE
Role failed on hosts which are not part of docker_ specific groups

### ISSUE THREAD

**Issue by nqb** [lefilament/ansible_role_docker_server#5]
Hello,

If you run this role on a host which is only part of `docker` group, Ansible will report following issue:

```
RUNNING HANDLER [docker_server : start inverseproxy docker] *******************************************************************************************************************************************************
fatal: [www]: FAILED! => changed=false 
[..]
  msg: |-
    Configuration error - The Compose file '/home/docker/inverseproxy/docker-compose.yaml' is invalid because:
    services.proxy.networks.shared contains null, which is an invalid type, it should be an array
```

Due to foilowing content in `/home/docker/inverseproxy/docker-compose.yaml`:

```yaml
version: "2.1"
services:
    proxy:
        image: traefik:v2.4
        container_name: inverseproxy
        environment:
            TZ: "Europe/Paris"
        networks:
            shared:
              aliases:
            smtp:
[..]
```

This is caused by the fact that your host should be *at least* member of one Docker group defined in inventory when [inverseproxy.yaml.j2](https://github.com/lefilament/ansible_role_docker_server/blob/4c97849d7ead09602c2059709fbc30c4f23099a3/templates/inverseproxy.yaml.j2#L11-L55) is evaluated.
